apiVersion: v1
kind: ConfigMap
metadata:
  name: devspaces-openshift-group-mapping
data:
  # JSON format mapping between OpenShift groups and Dev Spaces URLs
  group-mapping.json: |
    {
      "che-team-a": "https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com",
      "che-team-b": "https://devspaces-cluster1.example.com",
      "che-team-c": "https://devspaces-cluster2.example.com",
      "che-docs": "https://devspaces.apps.rm2.thpm.p1.openshiftapps.com",
      "interns": "https://workspaces.openshift.com"
    }
