apiVersion: v1
kind: ConfigMap
metadata:
  name: devspaces-openshift-group-mapping
data:
  # JSON format mapping between OpenShift groups and Dev Spaces URLs
  group-mapping.json: |
    {
      "che-team-a": "https://devspaces-cluster1.example.com",
      "che-team-b": "https://devspaces-cluster2.example.com",
      "che-team-c": "https://devspaces-cluster3.example.com",
      "che-docs": "https://devspaces-cluster4.example.com",
      "interns": "https://workspaces.openshift.com"
    }
