apiVersion: apps/v1
kind: Deployment
metadata:
  name: devspaces-multicluster-redirector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devspaces-multicluster-redirector
  template:
    metadata:
      labels:
        app: devspaces-multicluster-redirector
    spec:
      serviceAccountName: devspaces-multicluster-redirector
      containers:
        - name: devspaces-multicluster-redirector
          image: quay.io/redhat-developer/devspaces-multicluster-redirector:latest
          ports:
            - containerPort: 8080
        - name: oauth-proxy
          image: registry.redhat.io/openshift4/ose-oauth-proxy-rhel9@sha256:4da6381f4f79de6a6024554aa99129e9b79b7ad7fdde0b0bebbcb87421a97d7c
          ports:
            - containerPort: 8443
          args:
            - "-provider=openshift"
            - "-http-address=:8443"
            - "-https-address="
            - "-email-domain=*"
            - "-upstream=http://localhost:8080"
            - "-openshift-service-account=devspaces-multicluster-redirector"
            - "-client-id=system:serviceaccount:redirector:devspaces-multicluster-redirector"
            - '-openshift-sar={"nonResourceURL": "/", "verb": "get"}'
            - '-openshift-delegate-urls={"/":{"group": "user.openshift.io", "resource": "users", "name": "~", "verb": "get"}}'
            - "-client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token"
            - "-cookie-secret-file=/etc/proxy/secrets/session_secret"
          volumeMounts:
            - name: session-secret
              mountPath: /etc/proxy/secrets
      volumes:
        - name: session-secret
          secret:
            secretName: devspaces-multicluster-redirector-session-secret