apiVersion: v1
kind: Service
metadata:
  name: devspaces-multicluster-redirector
spec:
  selector:
    app: devspaces-multicluster-redirector
  ports:
    - name: https
      port: 443
      targetPort: 8443